name = "hyperspace-components"
version = "0.1.0"
defaultTargets = ["Solution"]
moreLeanArgs = ["-j1", "-M3072"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "065356127b1dc0016f66b7283ce0ce2c4055aa55"

[[lean_lib]]
name = "Boundary"

[[lean_lib]]
name = "Interior"

[[lean_lib]]
name = "Foundations"

[[lean_lib]]
name = "Checkpoint"

[[lean_lib]]
name = "Scalar"

[[lean_lib]]
name = "Hyperspace"

[[lean_lib]]
name = "Chain"

[[lean_lib]]
name = "Parameter"

[[lean_lib]]
name = "OrderArc"

[[lean_lib]]
name = "PathUnion"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "Challenge"

